#Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele
a = input('Digite algo: ')
print('O tipo primitivo desse valor é?', type(a))
print('Só tem espaços? {}'.format(a.isspace()))
print('É um número? {}'.format(a.isnumeric()))
print('É alfabético? {}'.format(a.isalpha()))
print('É alfanúmerico? {}'.format(a.isalnum()))
print('É maiúsculas? {}'.format(a.isupper()))
print('É minúsculas? {}'.format(a.islower()))
print('É capitalizadas? {}'.format(a.istitle()))
print('Só tem espaços?{}'.format(a.isspace()))
print('É um decimal?{}'.format(a.isdecimal()))
